### ISSUE TITLE
"LoginFailedException: invalid_request" when signing in with Google

### ISSUE THREAD

**Issue by JBindi** [Wolfsblvt/BlossomsPokemonGoManager#192]
I've experienced this on two different systems. The authentication key is correct.

I get something along the lines of this:

> [08/11 05:01:43]: D/RequestHandler: Authenticated with static token
> [08/11 05:01:43]: D/GoogleUserCredentialProvider: 0
> [08/11 05:01:43]: Unable to login!
> [08/11 05:01:43]: com.pokegoapi.exceptions.LoginFailedException: invalid_request
> [08/11 05:01:43]:   at com.pokegoapi.auth.GoogleUserCredentialProvider.refreshToken(GoogleUserCredentialProvider.java:161)
> [08/11 05:01:43]:   at com.pokegoapi.auth.GoogleUserCredentialProvider.getAuthInfo(GoogleUserCredentialProvider.java:234)
> [08/11 05:01:43]:   at com.pokegoapi.api.PokemonGo.getAuthInfo(PokemonGo.java:106)
> [08/11 05:01:43]:   at com.pokegoapi.main.RequestHandler.resetBuilder(RequestHandler.java:258)
> [08/11 05:01:43]:   at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:174)
> [08/11 05:01:43]:   at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:289)
> [08/11 05:01:43]:   at java.lang.Thread.run(Unknown Source)

Anyone else experiencing something like this?

**Comment by Wolfsblvt** [comment]
Do you have the latest version of this Tool installed? Which one is it?
We had some login problems that got fixed with the latest alpha version.

**Comment by JBindi** [comment]
Thanks for the reply. Yeah I'm trying to log in with v0.1.2-alpha.1.
It's able to retrieve my username but still no luck as far as logging in goes.

**Comment by Wolfsblvt** [comment]
Do you try that from a working computer?
The tool seems to have problems with VPN networks or networks that are hidden behind strong Firewalls.
Try to deactivate your local Firewall maybe?

**Comment by xEcl1pse** [comment]
I have this problem. When i start pokemon on mobile, i have error "failed to get game data from the server"

**Comment by JBindi** [comment]
I've tried it from my desktop as well as my laptop, I made sure to disable the firewall and to be disconnected from my VPN. Still no luck.

Just to rule my router off the list, perhaps I can try again from a different wifi spot.
Once again, thanks for the help.

**Comment by xephael** [comment]
@xEcl1pse That's been confirmed to be a permanent ban, open a separate issue and be sure to include if you were using any other third party applications like bots.

Also possible duplicate issue of #66

**Comment by Cryptically** [comment]
Appears to happen when the application is left untouched for a long time.
On the dev version, v0.1.2-alpha.2, based on yesterdays.

```
[22:03:52]: D/RequestHandler: Authenticated with static token
[22:03:53]: Successfully logged in. Welcome, <>.
[22:03:54]: Stats: Lvl <> Valor player.
[22:03:54]: Pokédex - Types Caught: <> , Total Pokémon Caught: <> , Total Current Pokémon: <> (+<>  Eggs)
[03:12:11]: D/RequestHandler: Authenticated with static token
[03:12:11]: D/GoogleUserCredentialProvider: 0
[03:12:11]: com.pokegoapi.exceptions.LoginFailedException: invalid_request
[03:12:11]:     at com.pokegoapi.auth.GoogleUserCredentialProvider.refreshToken(GoogleUserCredentialProvider.java:161)
[03:12:11]:     at com.pokegoapi.auth.GoogleUserCredentialProvider.getAuthInfo(GoogleUserCredentialProvider.java:234)
[03:12:11]:     at com.pokegoapi.api.PokemonGo.getAuthInfo(PokemonGo.java:106)
[03:12:11]:     at com.pokegoapi.main.RequestHandler.resetBuilder(RequestHandler.java:258)
[03:12:11]:     at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:174)
[03:12:11]:     at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:289)
[03:12:11]:     at java.lang.Thread.run(Unknown Source)
[03:12:11]: Done refreshing Pokémon list
```

**Comment by Cryptically** [comment]
Just experience the same thing again, left it idle for 2hours.

**Comment by Wolfsblvt** [comment]
Yeah, seems to be connected to #66 then.
Guess we'll "fix" that with a more gracefully message and application restart.
I mean if you let it idling for too long guess you can love with a restart and new login?

**Comment by Wolfsblvt** [comment]
The last issue will be fixed with #66, and I guess the top ones aren't issues anymore?
I don't think so.
If that is still a problem, please answer here.
